### ISSUE TITLE
Get information on all sides

### ISSUE THREAD

**Issue by songqinghao** [pointwise/CaeUnsTAU#1]
Excuse me, recently I am developing the PointWise plugin. I am thinking that if I want to get the surface information, only in terms of time, should I get it faster through Cell or streamFace

**Comment by dbgarlisch** [comment]
I have not benchmarked the speed of these two approaches. However, I suspect face streaming will always be slower due to the additional processing required to decompose the volume elements and match their faces to the boundary faces. How much slower, I do not know.

However, depending on the needs of your target mesh format, you may need to use streaming. It depends on several factors.

If the exported boundary faces do NOT need to be associated with their adjacent, owner, volume cells and you don't care if a boundary patch spans multiple volume zones (VCs), then accessing the boundaries will most likely be faster via:
* C: [PwModEnumDomains()][C-MED] and [PwDomEnumElements()][C-DEE]
* C++: [CaeUnsGridModel][CPP-GM] and [CaeUnsPatch][CPP-UP]

If you DO need the boundary patch faces grouped by certain criteria (see [PWGM_ENUM_FACEORDER][EFO]) or associated with their adjacent, owner, volume cells, then use face streaming via:
* C: [PwModStreamFaces()][C-MSF], [PwModEnumElements()][C-MEE], and [PwElemDataModEnum()][C-EDEM]
* C++: [CaeUnsGridModel::streamFaces()][CPP-MSF], [CaeUnsElement][CPP-UE], and [CaeUnsGridModel::appendEnumElementOrder][CPP-MAEEO]



[EFO]: http://www.pointwise.com/doc/plugins/html/dc/d28/group__DOXGRP__APIPWGM__TYPES.html#ga9aa04c377674244212e90e4af4b34a6f

[C-MED]: http://www.pointwise.com/doc/plugins/html/de/ded/group__DOXGRP__APIPWGM__FUNCTIONS__EXP__UNS.html#ga9396f34ad34fc35f5e832cf9428f2338

[C-DEE]: http://www.pointwise.com/doc/plugins/html/de/ded/group__DOXGRP__APIPWGM__FUNCTIONS__EXP__UNS.html#gaf6427263441fc5592eb6730596e379a3

[C-MSF]: http://www.pointwise.com/doc/plugins/html/de/ded/group__DOXGRP__APIPWGM__FUNCTIONS__EXP__UNS.html#gac5a18ffc302db9699c2cd5b6bb6280f2

[C-MEE]: http://www.pointwise.com/doc/plugins/html/de/ded/group__DOXGRP__APIPWGM__FUNCTIONS__EXP__UNS.html#gac0748224b239e2cb39f9cae5fb22ed9c

[C-EDEM]: http://www.pointwise.com/doc/plugins/html/de/ded/group__DOXGRP__APIPWGM__FUNCTIONS__EXP__UNS.html#ga1bba37630ebc3d187f83b418c694df7f

[CPP-GM]: http://www.pointwise.com/doc/plugins/html/de/da3/classCaeUnsGridModel.html

[CPP-UP]: http://www.pointwise.com/doc/plugins/html/dd/d57/classCaeUnsPatch.html

[CPP-MSF]: http://www.pointwise.com/doc/plugins/html/df/d12/CaeUnsGridModel_8cxx_source.html#l00072

[CPP-UE]: http://www.pointwise.com/doc/plugins/html/d5/d96/classCaeUnsElement.html

[CPP-MAEEO]: http://www.pointwise.com/doc/plugins/html/de/da3/classCaeUnsGridModel.html#ac6673e4553330b27a5bdc9c703e66f74

**Comment by songqinghao** [comment]
Thanks for your answer, I have roughly understood what to do, I will try to get the information I want without `streamFace.`
